# Generated by Django 5.2.4 on 2025-07-30 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='program',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.program'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course'),
        ),
    ]
